import React, { useEffect, useState } from 'react';
import { addShop, deleteShop, getAllShops, getShopkeeperApplications, reviewShopkeeperApplication } from '../services/api';

const blankShop = { name: '', ownerName: '', phone: '', address: '', pincode: '', licenseNumber: '', lat: 17.385, lng: 78.486, is24hr: false };
export default function AdminDashboard() {
  const [shops, setShops] = useState([]), [applications, setApplications] = useState([]), [form, setForm] = useState(blankShop), [message, setMessage] = useState(''), [licensePreview, setLicensePreview] = useState(null);
  const load = async () => { try { const [s, a] = await Promise.all([getAllShops(), getShopkeeperApplications()]); setShops(s.data); setApplications(a.data); } catch { setMessage('Could not load admin data.'); } };
  useEffect(() => { load(); }, []);
  const review = async (id, status) => { await reviewShopkeeperApplication(id, status, form.lat, form.lng); setMessage(`Application ${status.toLowerCase()}.`); load(); };
  const create = async e => { e.preventDefault(); await addShop(form); setForm(blankShop); setMessage('Shop added to MediFind.'); load(); };
  const remove = async shop => { if (!window.confirm(`Delete ${shop.name} from the database?`)) return; await deleteShop(shop.id); setMessage('Shop deleted.'); load(); };
  return <main className="portal-page"><header className="portal-heading"><div><span>ADMIN CONTROL</span><h1>Shop safety & approvals</h1><p>Verify licenses and maintain the trusted medical-shop database.</p></div><div className="metric"><b>{shops.length}</b><small>Active shops</small></div><div className="metric warning"><b>{applications.filter(a => a.approvalStatus === 'PENDING').length}</b><small>Pending reviews</small></div></header>
    {message && <div className="portal-message">{message}</div>}
    <section className="portal-grid"><div className="portal-card wide"><div className="card-title"><h2>Shopkeeper applications</h2><span>License verification required</span></div>
      {applications.length === 0 ? <p className="muted">No applications yet.</p> : applications.map(a => <article className="application-row" key={a.id}><div><b>{a.shopName}</b><small>{a.name} · {a.phone}</small><small>{a.shopAddress} — {a.pincode}</small><span className={`status ${a.approvalStatus.toLowerCase()}`}>{a.approvalStatus}</span></div><div className="application-actions">{a.licensePhoto && <button type="button" onClick={() => setLicensePreview(a)}>View license</button>}{a.approvalStatus === 'PENDING' && <><button onClick={() => review(a.id, 'APPROVED')}>Approve</button><button className="danger" onClick={() => review(a.id, 'REJECTED')}>Reject</button></>}</div></article>)}
    </div><form className="portal-card" onSubmit={create}><div className="card-title"><h2>Add a medical shop</h2></div>{Object.keys(blankShop).filter(k => k !== 'is24hr').map(k => <input key={k} type={['lat','lng'].includes(k) ? 'number' : 'text'} step="any" placeholder={k.replace(/([A-Z])/g,' $1')} required value={form[k]} onChange={e => setForm({...form,[k]: ['lat','lng'].includes(k) ? Number(e.target.value) : e.target.value})} />)}<label className="check"><input type="checkbox" checked={form.is24hr} onChange={e => setForm({...form,is24hr:e.target.checked})}/> Open 24 hours</label><button className="primary-action">Add shop</button></form></section>
    <section className="portal-card shop-table"><div className="card-title"><h2>All medical shops</h2><span>Admin can remove malicious listings</span></div><div className="table-scroll"><table><thead><tr><th>Shop</th><th>Owner</th><th>Location</th><th>Status</th><th></th></tr></thead><tbody>{shops.map(s => <tr key={s.id}><td><b>{s.name}</b><small>{s.phone}</small></td><td>{s.ownerName || '—'}</td><td>{s.address}<small>{s.pincode}</small></td><td><span className={`status ${s.isOpen ? 'approved':'pending'}`}>{s.isOpen ? 'OPEN':'CLOSED'}</span></td><td><button className="delete-link" onClick={() => remove(s)}>Delete</button></td></tr>)}</tbody></table></div></section>
    {licensePreview && <div className="license-modal" role="dialog" aria-modal="true" onClick={() => setLicensePreview(null)}><div className="license-dialog" onClick={e => e.stopPropagation()}><div className="license-dialog-header"><div><span>MEDICAL LICENSE</span><h2>{licensePreview.shopName}</h2><small>{licensePreview.licenseNumber || 'License number not provided'}</small></div><button onClick={() => setLicensePreview(null)} aria-label="Close">×</button></div><div className="license-image-wrap"><img src={licensePreview.licensePhoto} alt={`${licensePreview.shopName} medical license`} onError={e => { e.currentTarget.style.display = 'none'; e.currentTarget.nextElementSibling.style.display = 'grid'; }} /><div className="license-image-error"><b>Image could not be displayed</b><small>Please ask the shopkeeper to upload the license again as a JPG or PNG image.</small></div></div><div className="license-dialog-footer"><span>Submitted by {licensePreview.name}</span><button onClick={() => setLicensePreview(null)}>Close preview</button></div></div></div>}
  </main>;
}
