import React, { useEffect, useState } from 'react';
import { createBill, getDailyBills, toggleShopStatus } from '../services/api';

const blank = { customerName: '', medicineName: '', quantity: 1, price: '', sgst: '', cgst: '', serviceTax: '' };
export default function ShopkeeperDashboard() {
  const shopId = localStorage.getItem('shopId');
  const [form, setForm] = useState(blank), [report, setReport] = useState({ bills: [], billCount: 0, medicinesSold: 0, revenue: 0 }), [date, setDate] = useState(new Date().toISOString().slice(0,10)), [isOpen, setIsOpen] = useState(false), [message, setMessage] = useState('');
  const load = async () => { if (!shopId) return setMessage('No approved shop is linked to this account.'); try { setReport((await getDailyBills(shopId, date)).data); } catch { setMessage('Could not load daily billing report.'); } };
  useEffect(() => { load(); }, [date]);
  const submit = async e => { e.preventDefault(); try { await createBill(shopId, { ...form, quantity: Number(form.quantity), price: Number(form.price), sgst: Number(form.sgst || 0), cgst: Number(form.cgst || 0), serviceTax: Number(form.serviceTax || 0) }); setForm(blank); setMessage('Bill saved and included in today’s report.'); load(); } catch (err) { setMessage(err.response?.data || 'Could not save bill.'); } };
  const toggle = async () => { try { await toggleShopStatus(shopId, !isOpen); setIsOpen(!isOpen); } catch { setMessage('Could not update shop status.'); } };
  const previewTotal = (Number(form.price || 0) * Number(form.quantity || 1) + Number(form.sgst || 0) + Number(form.cgst || 0) + Number(form.serviceTax || 0)).toFixed(2);
  return <main className="portal-page"><header className="portal-heading"><div><span>SHOPKEEPER DESK</span><h1>Daily billing</h1><p>Record medicine sales and monitor your day at a glance.</p></div><button className={`shop-status-toggle ${isOpen ? 'open':''}`} onClick={toggle}><i/>{isOpen ? 'Shop open' : 'Shop closed'}</button></header>
    {message && <div className="portal-message">{message}</div>}
    <section className="summary-cards"><div><small>Bills today</small><b>{report.billCount}</b></div><div><small>Medicines sold</small><b>{report.medicinesSold}</b></div><div><small>Today’s revenue</small><b>₹{Number(report.revenue).toFixed(2)}</b></div></section>
    <section className="portal-grid billing-grid"><form className="portal-card" onSubmit={submit}><div className="card-title"><h2>Create customer bill</h2><span>Date and time are recorded automatically</span></div><input placeholder="Customer name (optional)" value={form.customerName} onChange={e => setForm({...form,customerName:e.target.value})}/><input placeholder="Medicine name" required value={form.medicineName} onChange={e => setForm({...form,medicineName:e.target.value})}/><div className="split-fields"><input type="number" min="1" placeholder="Quantity" required value={form.quantity} onChange={e => setForm({...form,quantity:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Unit price ₹" required value={form.price} onChange={e => setForm({...form,price:e.target.value})}/></div><div className="tax-grid"><input type="number" min="0" step="0.01" placeholder="SGST ₹" value={form.sgst} onChange={e => setForm({...form,sgst:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="CGST ₹" value={form.cgst} onChange={e => setForm({...form,cgst:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Service tax ₹" value={form.serviceTax} onChange={e => setForm({...form,serviceTax:e.target.value})}/></div><div className="bill-total"><span>Bill total</span><b>₹{previewTotal}</b></div><button className="primary-action">Save bill</button></form>
      <div className="portal-card wide"><div className="card-title"><div><h2>Sales report</h2><span>Medicine-wise daily transaction data</span></div><input className="date-picker" type="date" value={date} onChange={e => setDate(e.target.value)}/></div><div className="table-scroll"><table><thead><tr><th>Time</th><th>Medicine</th><th>Qty</th><th>Taxes</th><th>Total</th></tr></thead><tbody>{report.bills.map(b => <tr key={b.id}><td>{new Date(b.billedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td><td><b>{b.medicineName}</b><small>{b.customerName || 'Walk-in customer'}</small></td><td>{b.quantity}</td><td>₹{(Number(b.sgst)+Number(b.cgst)+Number(b.serviceTax)).toFixed(2)}</td><td><b>₹{Number(b.total).toFixed(2)}</b></td></tr>)}{!report.bills.length && <tr><td colSpan="5" className="empty-cell">No bills recorded for this date.</td></tr>}</tbody></table></div></div>
    </section>
  </main>;
}
